In [1]:
import torch

In [2]:
a = torch.ones((2,2),requires_grad = True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
a.requires_grad

True

In [5]:
# Alternative way
# Kinda useful if you want to compute without gradients first and then add gradients later
# I don't know why you would do that

b = torch.ones((2,2))
print(b)
b.requires_grad_()

b

tensor([[1., 1.],
        [1., 1.]])


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [10]:
# Manually create gradients
x = torch.ones(2,requires_grad= True)
print(x)

y = 5 * (x + 1)**2

o = (1/2)*torch.sum(y)
o

tensor([1., 1.], requires_grad=True)


tensor(20., grad_fn=<MulBackward0>)

In [11]:
o.backward()
x.grad

tensor([10., 10.])