In [0]:
#setup to make lives easier 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [0]:
import torch

In [2]:
#Uninitialized matrix
x = torch.empty(2,4)
print(x)

tensor([[3.2440e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 6.1657e-44, 1.1578e+27, 1.1362e+30]])


In [4]:
# Randomly initialized matrix
x = torch. rand(2,2)
print(x)

tensor([[0.6572, 0.7369],
        [0.9291, 0.9567]])


In [7]:
# Zero Matrix
z = torch.zeros(5,2,dtype=torch.long)
print(z)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [9]:
# Create tensor directly
data = torch.tensor([5.5,3])
print(data)

tensor([5.5000, 3.0000])


In [15]:
# Modify tensor to new tensor
z = z.new_ones(5,3,dtype = torch.long)
print(z)

w = torch.randn_like(z,dtype=torch.float)
print(w)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[ 0.2894,  1.2148, -0.8083],
        [-0.2251, -0.2568, -1.6140],
        [ 0.9745,  0.0459, -0.1145],
        [ 0.9111, -0.7175, -0.1710],
        [-0.5059, -0.1128, -0.7801]])


In [16]:
# Get size
print(w.size())

torch.Size([5, 3])


In [19]:
# Addition syntaxes
y = torch.rand(5,3)
print(z+y)

print(torch.add(y,z))

result = torch.empty(5,3)
torch.add(y,z,out=result)
print(result)

tensor([[1.2173, 1.8972, 1.8407],
        [1.8279, 1.3294, 1.4555],
        [1.5609, 1.0814, 1.8565],
        [1.3664, 1.2265, 1.2670],
        [1.3382, 1.7115, 1.0003]])
tensor([[1.2173, 1.8972, 1.8407],
        [1.8279, 1.3294, 1.4555],
        [1.5609, 1.0814, 1.8565],
        [1.3664, 1.2265, 1.2670],
        [1.3382, 1.7115, 1.0003]])


tensor([[1.2173, 1.8972, 1.8407],
        [1.8279, 1.3294, 1.4555],
        [1.5609, 1.0814, 1.8565],
        [1.3664, 1.2265, 1.2670],
        [1.3382, 1.7115, 1.0003]])

tensor([[1.2173, 1.8972, 1.8407],
        [1.8279, 1.3294, 1.4555],
        [1.5609, 1.0814, 1.8565],
        [1.3664, 1.2265, 1.2670],
        [1.3382, 1.7115, 1.0003]])


In [20]:
# Inplace addition
a = torch.zeros(5,3)
b = torch.ones(5,3)
b.add_(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [21]:
# Resizing with torch.view
a = torch.rand(4,4)
b = a.view(16)
c = a.view(-1,8)
print("{} {} {}".format(a.size(),b.size(),c.size()))

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [24]:
# tensor to numpy bridge
a = torch.ones(5)
b = a.numpy()
print("{} {}".format(a,b))

# Pass by reference caveat
a.add_(1)
print("{} {}".format(a,b))

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


tensor([2., 2., 2., 2., 2.])

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [25]:
# Numpy to tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)

# Pass by reference caveat
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


array([2., 2., 2., 2., 2.])

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
if torch.cuda.is_available():
  device = torch.device()
  b = torch.ones_like(a)
  a = a.to(device)
  ans = a + b
  print(ans)
  print(ans.to("cpu",torch.double))