<a href="https://colab.research.google.com/github/AnupJoseph/learn-pytorch/blob/master/LearnPytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [3]:
# Create a tensor with tracked gradient computation
x = torch.ones(3,3,requires_grad = True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [5]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [6]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27., 27.],
        [27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [9]:
# Use requires_grad_ function attribute over a Tensor to compute gradients from a certain point
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)

# set requires grad to true
a.requires_grad_(True)
print(a.requires_grad)

# Create a new variable using a .This variable will have a as its grad_fn
b = (a*a).sum()
print(b)
print(b.grad_fn)

False
True
tensor(1.9892, grad_fn=<SumBackward0>)


In [10]:
out.backward()
print(x.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
