In [2]:
a = [[1,2],[1,2]]
print(a)

import numpy as np
np.array(a)

import torch 
torch.Tensor(a)

[[1, 2], [1, 2]]


tensor([[1., 2.],
        [1., 2.]])

In [3]:
print(np.ones((2,2)))

torch.ones((2,2))

[[1. 1.]
 [1. 1.]]


tensor([[1., 1.],
        [1., 1.]])

In [4]:
np.random.rand(2 ,4)
torch.rand(2,4)

tensor([[0.7387, 0.1301, 0.0612, 0.6582],
        [0.3340, 0.4152, 0.4062, 0.9506]])

##### Seeds

Seeds are used to reproduce randomly valued results.Seeds allow to repeat exact outputs in random values

In [5]:
np.random.seed(0)
np.random.rand(2, 4)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ]])

In [6]:
torch.manual_seed(0)
torch.rand((2,4))

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964]])

In [7]:
# Fixing seed for GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed_all()

In [8]:
arr = np.ones((2,2))
print(arr)

arrz = torch.from_numpy(arr)
print(arrz)

# Catch not all numpy datatypes are supported
# only the following are int64, int32, uint8, double, float
# Types conversions are
# int64 -> torch.LongTensor
# int32 -> torch.IntTensor
# unit8 -> torch.ByteTensor
# float,double -> torch.DoubleTensor

[[1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [9]:
arr = torch.ones(2,4)
print(arr)

arrz = arr.numpy()
print(arrz)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
a = torch.Tensor(2,2)
a.size()
a.view(4,1)

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [25]:
a = torch.ones(2,2)
b = torch.rand((2,2))
c = a+b

# Alternative method
c = torch.add(a,b)

# Doing it inplace to save the day
b.add_(a)

tensor([[1.1852, 1.3734],
        [1.3051, 1.9320]])

In [29]:
a = torch.ones(2,2)
b = torch.rand((2,2))
c = a - b

c = torch.sub(a,b)

c.sub_(a)

tensor([[-0.1387, -0.2422],
        [-0.8155, -0.7932]])

In [33]:
a = torch.ones(2,2)
b = torch.rand((2,1))

c =a*b

c = torch.mul(a,b)

c.mul_(a)

tensor([[0.8352, 0.8352],
        [0.2056, 0.2056]])

In [39]:
a = torch.ones(2,2)
b = torch.rand((2,2))

c = b/a

c = torch.div(b,a)

c.div_(b)

tensor([[1., 1.],
        [1., 1.]])

In [41]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.mean(dim=0)

tensor(5.5000)

In [42]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

tensor(3.0277)