In [5]:
a = [[1,2],[1,2]]
print(a)

import numpy as np
np.array(a)

import torch 
torch.Tensor(a)

[[1, 2], [1, 2]]


tensor([[1., 2.],
        [1., 2.]])

In [8]:
print(np.ones((2,2)))

torch.ones((2,2))

[[1. 1.]
 [1. 1.]]


tensor([[1., 1.],
        [1., 1.]])

In [11]:
np.random.rand(2 ,4)
torch.rand(2,4)

tensor([[0.9253, 0.4502, 0.1198, 0.2995],
        [0.8968, 0.1334, 0.2180, 0.2078]])

##### Seeds

Seeds are used to reproduce randomly valued results.Seeds allow to repeat exact outputs in random values

In [12]:
np.random.seed(0)
np.random.rand(2, 4)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ]])

In [13]:
torch.manual_seed(0)
torch.rand((2,4))

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964]])